import './globals.css';
import NextAuthProvider from '../components/SessionProvider';
import { FloatingDock } from '../components/ui/floating-dock';
import { Home, BarChart, Trophy } from 'lucide-react';
import { GlobalHeader } from '../components/GlobalHeader';
import { ThemeProvider } from "next-themes";
import { Footer } from '../components/Footer'; 

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  const navItems = [
    {
      title: 'Home',
      href: '/events',
      icon: <Home className="h-4 w-4 text-neutral-500 dark:text-neutral-400" />,
    },
    {
      title: 'Leaderboard',
      href: '/leaderboard',
      icon: <BarChart className="h-4 w-4 text-neutral-500 dark:text-neutral-400" />,
    },
    {
      title: 'Results',
      href: '/results',
      icon: <Trophy className="h-4 w-4 text-neutral-500 dark:text-neutral-400" />,
    },
  ];

return (
    <html lang="en" suppressHydrationWarning>
      <head />
      <body className="flex flex-col min-h-screen">
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
          <NextAuthProvider>
            <GlobalHeader />
            <main className="flex-grow">
              {children}
            </main>
            <Footer />
            <div className="fixed bottom-10 left-0 right-0 z-50 flex justify-center">
              <FloatingDock items={navItems} />
            </div>
          </NextAuthProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}